version: '3.7'

services:
  # backend:
  #   build: .
  #   ports:
  #     - 5501:5501
  #     - 8080:8080
  #   env_file:
  #     - .env.production
  #   environment:
  #     - NODE_ENV=production
  #     - MONGODB_HOST=mongo
  #     - MONGODB_PORT=27017
  #     - MONGODB_USER=coinpixel_user
  #     - MONGODB_PASS=12345
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   depends_on:
  #     - mongo
  #     - redis
  #   links:
  #     - mongo
  #     - redis
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=coinpixel_user
      - MONGO_INITDB_ROOT_PASSWORD=12345
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=coinpixel_user
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_AOF_ENABLED=no
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 1024mb

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    depends_on:
      - redis
    links:
      - redis
  
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - backend